title: mein BAIN-Blog
author: Almira
email: almiramedaric@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hier bekommst du einen kleinen Einblick in meinem Lernprozess im Modul Bibliotheks- und Archivinformatik im Studiengang Information Science der Fachhochschule Graubünden (FHGR). Nach jeder Vorlesung werde ich über den Inhalts des Tages erzählen und mein persönliches Empfunden zum Thema beschreiben. Ich freue mich, dass du möchtest meine Erfahrung folgen!
# social links
github_username: sakura-72 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
